# Generated by Django 5.2.7 on 2025-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_alter_profile_full_name_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
