# Generated by Django 5.2.7 on 2025-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_user_otp_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="کد تایید"
            ),
        ),
    ]
