# Generated by Django 5.2.7 on 2026-01-07 15:39

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
import userauths.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="audience.jpg",
                        null=True,
                        upload_to="audience",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "audience",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ClothingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="clothing_type.jpg",
                        null=True,
                        upload_to="clothing_type",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "clothing_type",
                "ordering": ["title"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"], "verbose_name_plural": "Products"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="view",
            new_name="views",
        ),
        migrations.AddField(
            model_name="product",
            name="orders",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="saved",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=5,
                max_length=50,
                prefix="SKU",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="special_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.audience",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("Size", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("cart_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="paid",
                        max_length=100,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Processing"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "initial_total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh",
                        length=10,
                        max_length=12,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("Size", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "initial_total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh",
                        length=10,
                        max_length=12,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.cartorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="clothing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.clothingtype",
            ),
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color_code", models.CharField(max_length=100)),
                (
                    "color_text",
                    models.CharField(
                        blank=True, default="#ffffff", max_length=100, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=1000)),
                ("discount", models.IntegerField(default=1)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=25,
                        prefix="",
                    ),
                ),
                (
                    "used_by",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="/gallery.jpg",
                        upload_to=userauths.models.user_directory_path,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("gid", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.cartorder",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.cartorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification",
            },
        ),
        migrations.CreateModel(
            name="ProductFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Faqs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 star"),
                            (3, "3 star"),
                            (4, "4 star"),
                            (5, "5 star"),
                        ],
                        default=None,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", models.CharField(max_length=1000)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wishlist",
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
