# Generated by Django 5.2.7 on 2025-12-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_gallery_options_remove_gallery_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="audience.jpg",
                        null=True,
                        upload_to="audience",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "audience",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ClothingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="clothing_type.jpg",
                        null=True,
                        upload_to="clothing_type",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "clothing_type",
                "ordering": ["title"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.audience",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="clothing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.clothingtype",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
