# Generated by Django 5.2.7 on 2026-01-02 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_coupon_notification_productfaq_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Processing"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("cancelled", "Cancelled"),
                ],
                default="paid",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 star"),
                    (3, "3 star"),
                    (4, "4 star"),
                    (5, "5 star"),
                ],
                default=None,
            ),
        ),
    ]
