# Generated by Django 5.2.7 on 2026-01-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_review_active_review_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="rating",
        ),
    ]
