# Generated by Django 5.2.7 on 2026-01-03 13:41

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_product_options_product_orders_product_saved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="view",
            new_name="views",
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.FileField(
                default="gallery.jpg", upload_to=userauths.models.user_directory_path
            ),
        ),
    ]
