# Generated by Django 5.2.7 on 2026-01-06 16:58

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_view_product_views_alter_gallery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color_text",
            field=models.CharField(default="#ffffff", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallery",
            name="gid",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.FileField(
                default="/gallery.jpg", upload_to=userauths.models.user_directory_path
            ),
        ),
    ]
